#!/usr/bin/env bash
# Setup dotfiles

LINKFILES=(
    .aliases
    .bash_logout
    .bashrc
    .config/flake8
    .gitconfig
    .gitconfig_mainuser
    .gnupg/gpg-agent.conf
    .gnupg/gpg.conf
    .profile
    .zshrc
    .zprofile
    .zsh.d
)

COPYFILES=(
    .gnupg/sshcontrol
)

cd "$(dirname $0)"

for file in ${LINKFILES[@]}; do
    ln -fsT "$(pwd)"/"${file}" "${HOME}"/"${file}"
done

for file in ${COPYFILES[@]}; do
    cp --preserve=mode "$(pwd)"/"${file}" "${HOME}"/"${file}"
done
