#!/usr/bin/env -S bash -e -o pipefail
# Setup dotfiles

LINKFILES=(
    .aliases
    .bash_logout
    .bashrc
    .config/flake8
    .config/pep8
    .gitconfig
    .gitconfig_mainuser
    .gnupg/gpg-agent.conf
    .gnupg/gpg.conf
    .profile
    .ssh/config
    .zshrc
    .zprofile
    .zsh.d
)

COPYFILES=(
    .gnupg/sshcontrol
)

declare -A PERMISSIONS=(
    [".ssh"]="700"
    [".gnupg"]="700"
)

install_common() {
    sudo apt-get install -y \
        language-pack-ja \
        zsh
}

install_ansible() {
    ansible --version && return 0 || echo "Setup Ansible"
    pip3 --version || sudo apt-get install -y python3-pip
    pip3 install ansible ansible-lint
    ansible --version
}

install_nodejs() {
    node -v && return 0 || echo "Setup Node.js"

    sudo apt-get install -y \
        nodejs \
        npm

    sudo npm install n --location=global
    sudo n stable

    sudo apt-get purge -y \
        nodejs \
        npm

    exec $SHELL -l

    node -v
}

cd "$(dirname $0)"

for file in ${LINKFILES[@]}; do
    target="${HOME}"/"${file}"
    mkdir -p $(dirname "${target}")
    ln -fsT "$(pwd)"/"${file}" "${target}"
done

for file in ${COPYFILES[@]}; do
    target="${HOME}"/"${file}"
    mkdir -p $(dirname "${target}")
    cp --preserve=mode "$(pwd)"/"${file}" "${target}"
done

for target in "${!PERMISSIONS[@]}"; do
    chmod "${PERMISSIONS[${target}]}" "${target}"
done

sudo apt-get update

install_common
install_ansible
install_nodejs

sudo chsh -s "$(which zsh)" "$(whoami)"
