#!/usr/bin/env -S bash -e -o pipefail
# Setup dotfiles

umask 022

LINKFILES=(
    .aliases
    .bash_logout
    .bashrc
    .config/flake8
    .config/pep8
    .gitconfig
    .gitconfig_mainuser
    .gnupg/gpg-agent.conf
    .gnupg/gpg.conf
    .profile
    .ssh/config
    .zshrc
    .zprofile
    .zsh.d
)

DIRECTORIES=(
    repos
    subrepos
)

COPYFILES=(
    .gnupg/sshcontrol
)

declare -A PERMISSIONS=(
    [".ssh"]="700"
    [".gnupg"]="700"
)

install_common() {
    sudo apt-get install -y \
        language-pack-ja \
        zsh
}

install_python() {
    flake8 --version && mypy --version && return 0 || echo "Setup Python"
    sudo apt-get install -y python3 python3-pip
    pip3 install flake8 mypy
}

install_ansible() {
    ansible --version && return 0 || echo "Setup Ansible"
    pip3 --version || sudo apt-get install -y python3-pip
    pip3 install ansible ansible-lint
}

install_nodejs() {
    node -v && return 0 || echo "Setup Node.js"

    sudo apt-get install -y \
        nodejs \
        npm

    sudo npm install n --location=global
    sudo n stable

    sudo apt-get purge -y \
        nodejs \
        npm
}

cd "$(dirname "$0")"

for file in "${LINKFILES[@]}"; do
    target="${HOME}"/"${file}"
    mkdir -p "$(dirname "${target}")"
    ln -fsT "$(pwd)"/"${file}" "${target}"
done

for file in "${COPYFILES[@]}"; do
    target="${HOME}"/"${file}"
    mkdir -p "$(dirname "${target}")"
    cp --preserve=mode "$(pwd)"/"${file}" "${target}"
done

for dir in "${DIRECTORIES[@]}"; do
    target="${HOME}"/"${dir}"
    mkdir -p "${target}"
done

for target in "${!PERMISSIONS[@]}"; do
    chmod "${PERMISSIONS[${target}]}" "${target}"
done

sudo apt-get update

install_common
install_python
install_ansible
install_nodejs

sudo chsh -s "$(which zsh)" "$(whoami)"
