---
name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Setup
        run: |
          sudo apt-get update
          ./setup
      - name: Test
        run: |
          bash -e -o pipefail .profile
          bash -e -o pipefail .bash_logout
          zsh -e -o pipefail .zprofile
